add step
Signed-off-by: Yanxuan Liu <yanxuanl@nvidia.com>

diff --git a/markdown-link-check/action.yml b/markdown-link-check/action.yml
--- a/markdown-link-check/action.yml
+++ b/markdown-link-check/action.yml
@@ -26,10 +26,30 @@ runs:
         use-verbose-mode: 'yes'
         base-branch: 'gh-pages'
     
-    - name: Save output
+    - name: Summarize results
       shell: bash
       if: always()
       run: |
-        echo "========= test start =========="
-        echo "$MLC_OUTPUT"
-        echo "========= test end =========="
+        if grep -q 'ERROR:' <<< "$MLC_OUTPUT"; then
+          echo "Found broken links:"
+          echo "-------------------------------"
+          
+          echo "$MLC_OUTPUT" | grep -E '(FILE:|ERROR:)' | while read -r line; do
+            if [[ $line == FILE:* ]]; then
+              current_file="${line#FILE: }"
+            elif [[ $line == *ERROR:* ]]; then
+              link=$(echo "$line" | sed -E 's/.*https?:\/\/[^ ]+//; s/ .*//')
+              status=$(echo "$line" | grep -oE 'status: [0-9]+' | cut -d' ' -f2)
+              
+              printf "%s\n%s\n%s\n\n" \
+                "$current_file" \
+                "$link" \
+                "Status: $status"
+            fi
+          done
+          
+          echo "-------------------------------"
+          exit 1
+        else
+          echo "All links are valid"
+        fi
